export const data = [
  {
    requisition_number: 15646,
    job_title: 'Web',
    department: 'Department 1',
    location: 'Dubai / UAE',
    recruiter_name: 'Recruiter 1',
    recruiter_email: 'recruiter@gmail.com',
  },
  {
    requisition_number: 151,
    job_title: 'Sales',
    department: 'Department 2',
    location: 'Dubai / UAE',
    recruiter_name: 'Recruiter 2',
    recruiter_email: 'recruiter@gmail.com',
  },
  {
    requisition_number: 132154,
    job_title: 'Manager',
    department: 'Department 3',
    location: 'Dubai / UAE',
    recruiter_name: 'Recruiter 3',
    recruiter_email: 'recruiter@gmail.com',
  },
  {
    requisition_number: 185464,
    job_title: 'Senior',
    department: 'Department 4',
    location: 'Dubai / UAE',
    recruiter_name: 'Recruiter 4',
    recruiter_email: 'recruiter@gmail.com',
  },
  {
    requisition_number: 14864,
    job_title: 'Head',
    department: 'Department 5',
    location: 'Dubai / UAE',
    recruiter_name: 'Recruiter 5',
    recruiter_email: 'recruiter@gmail.com',
  },
  {
    requisition_number: 146846,
    job_title: 'Sales',
    department: 'Department 6',
    location: 'Dubai / UAE',
    recruiter_name: 'Recruiter 6',
    recruiter_email: 'recruiter@gmail.com',
  },
  {
    requisition_number: 485464,
    job_title: 'Store Keeper',
    department: 'Department 7',
    location: 'Dubai / UAE',
    recruiter_name: 'Recruiter 7',
    recruiter_email: 'recruiter@gmail.com',
  },
];
