export const data = [
  {
    requisition_number: 1231,
    job_title: 'Visual Merchandiser',
    department: 'LC Waikiki',
    location: 'Dubai, UAE',
    recruiter_name: 'Mona',
    recruiter_email: 'mona.shah@apparelglobal.com',
  },
  {
    requisition_number: 1681,
    job_title: 'Marketing Executive',
    department: 'Marketing Office KSA',
    location: 'Jeddah, KSA',
    recruiter_name: 'Afsar',
    recruiter_email: 'afsar.mohamed@apaprelglobal.com',
  },
  {
    requisition_number: 4068,
    job_title: 'Manager - Planning',
    department: 'Nysaa Office - UAE',
    location: 'Dubai, UAE',
    recruiter_name: 'Sarah',
    recruiter_email: 'sarah.murethi@apparelglobal.com',
  },
  {
    requisition_number: 4040,
    job_title: 'Service Crew',
    department: 'Tim Hortons Sales & Operations',
    location: 'KSA',
    recruiter_name: 'Sarah',
    recruiter_email: 'sarah.murethi@apparelglobal.com',
  },
  {
    requisition_number: 4041,
    job_title: 'Supervisor',
    department: 'Tim Hortons Sales & Operations',
    location: 'KSA',
    recruiter_name: 'Sarah',
    recruiter_email: 'sarah.murethi@apparelglobal.com',
  },
  {
    requisition_number: 3550,
    job_title: 'Executive - Logistics',
    department: 'Birkenstock',
    location: 'UAE',
    recruiter_name: 'Sarah',
    recruiter_email: 'sarah.murethi@apparelglobal.com',
  },
  {
    requisition_number: 3770,
    job_title: 'Buyer',
    department: 'Brand Bazaar',
    location: 'UAE',
    recruiter_name: 'Sarah',
    recruiter_email: 'sarah.murethi@apparelglobal.com',
  },
];
