// =CONCATENATE("{requisition_number:",A2,",job_title:'",B2,"',department:'",C2,"',location:'",D2,"',recruiter_email:'",E2,"',},")
export const dataFromFile = [
  {
    requisition_number: 101010,
    job_title: 'Test',
    department: 'Test Brand',
    location: 'UAE',
    recruiter_email: 'rabee.aljaramani@apparelglobal.com',
  },
  {
    requisition_number: 1231,
    job_title: 'Visual Merchandiser',
    department: 'LC Waikiki',
    location: 'UAE',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 1310,
    job_title: 'Sales Associate - BHPC',
    department: 'Beverly Hills Polo Club Al Othaim Mall - Dammam',
    location: 'Riyadh, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 1413,
    job_title: 'Sales Associate',
    department: 'Brand Bazaar',
    location: 'UAE',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 1358,
    job_title: 'Line Cook',
    department: 'Sushi Library KSA Office',
    location: 'Dammam, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 1359,
    job_title: 'Commis Chef',
    department: 'Sushi Library KSA Office',
    location: 'Dammam, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 1360,
    job_title: 'Brand Executive',
    department: 'ECommerce UAE',
    location: 'Dubai, UAE',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 1483,
    job_title: 'Sales Associate',
    department: 'Adidas',
    location: 'KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 1557,
    job_title: 'Sales Associate - Aeropostale',
    department: 'Aeropostale Mall Of Dhahran',
    location: 'KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 1620,
    job_title: 'Sales Associate - Crocs -Riyadh',
    department: 'Crocs Nakheel Mall - Riyadh',
    location: 'KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 1692,
    job_title: 'Assistant Store Manager - Tommy - Riyadh',
    department: 'Tommy Hilfiger Riyadh Park Mall',
    location: 'Riyadh, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 1631,
    job_title: 'Merchandiser',
    department: 'LC Waikiki',
    location: 'UAE',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 1681,
    job_title: 'Marketing Executive',
    department: 'Marketing Office KSA',
    location: 'Jeddah, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 1864,
    job_title: 'Sales Associate - R&B - Riyadh',
    department: 'R&B',
    location: 'Riyadh, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 1830,
    job_title: 'Visual Merchandiser',
    department: 'Sales UAE',
    location: 'UAE',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 1825,
    job_title: 'Sales Associate',
    department: 'New Yorker',
    location: 'UAE',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 1961,
    job_title: 'Store Manager - Riyadh',
    department: 'Crocs Galeria Mall-Riyadh',
    location: 'Riyadh, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 1966,
    job_title: 'Executive - Accounts',
    department: 'Accounts and Finance KSA',
    location: 'Riyadh, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 2057,
    job_title: 'Sales Associate - Dune - Riyadh',
    department: 'Dune Nakheel Mall Riyadh',
    location: 'Riyadh, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 2023,
    job_title: 'Sales Associate - ACO - Riyadh',
    department: 'The Athlete Foot Granada Mall Riyadh',
    location: 'Riyadh, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 2240,
    job_title: 'Sales Associate - Hema',
    department: 'Hema Mall of Dhahran',
    location: 'Dammam, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 2199,
    job_title: 'Sales Associate - Ath',
    department: 'The Athlete Foot Dareen Mall',
    location: 'Dammam, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 2162,
    job_title: 'Sales Associate - Toms',
    department: 'TOMS Mall of  Dhahran',
    location: 'Dammam, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 2251,
    job_title: 'Translator- 6th street',
    department: 'X Ecommerce X',
    location: 'Riyadh, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4164,
    job_title: 'Area Visual Merchandiser',
    department: 'R&B Head Office KSA',
    location: 'Riyadh, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 3992,
    job_title: 'Brand Coordinator',
    department: 'Brand Bazaar',
    location: 'UAE',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 3635,
    job_title: 'Store Manager',
    department: 'Birkenstock',
    location: 'UAE',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4061,
    job_title: 'Store Manager',
    department: 'Tim Hortons Sales & Operations',
    location: 'KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 2259,
    job_title: 'Sales Associate - Adidas',
    department: 'Adidas',
    location: 'KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4040,
    job_title: 'Service Crew',
    department: 'Tim Hortons Sales & Operations',
    location: 'KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4041,
    job_title: 'Supervisor',
    department: 'Tim Hortons Sales & Operations',
    location: 'KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 3770,
    job_title: 'Buyer',
    department: 'Brand Bazaar',
    location: 'UAE',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4237,
    job_title: 'Sales Associate',
    department: 'HIS & HERS - Dalma Mall',
    location: 'UAE',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 3980,
    job_title: 'Commercial Manager',
    department: 'Accounts and Finance KSA',
    location: 'Riyadh, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 3386,
    job_title: 'Visual Merchandiser',
    department: 'R&B Al Salaam Mall',
    location: 'Jeddah, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 2524,
    job_title: 'Waiter - Jamies',
    department: 'Jamies Italian Nakheel Mall - Dammam',
    location: 'Dammam, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 3532,
    job_title: 'Senior Store Manager',
    department: 'R&B Al Qasr Mall - Riyadh',
    location: 'KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 2545,
    job_title: 'Sales Associate - BHPC',
    department: 'Beverly Hills Polo Club Dareen Mall - Dammam',
    location: 'Dammam, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 3654,
    job_title: 'Sales Associate',
    department: 'Skechers Al Qasr Mall - Riyadh',
    location: 'Riyadh, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 2341,
    job_title: 'Waiter - Jim',
    department: 'Jamies Italian Nakheel Mall - Dammam',
    location: 'Dammam, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 3368,
    job_title: 'Stock Coordinator',
    department: 'Human Capital KSA',
    location: 'Jeddah, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 3636,
    job_title: 'Stock Coordinator',
    department: 'Birkenstock',
    location: 'UAE',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 3500,
    job_title: 'Assistant Store Manager - Riyadh',
    department: 'Levis Hayat Mall - Riyadh',
    location: 'KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 3041,
    job_title: 'Sales Associate',
    department: 'Birkenstock',
    location: 'UAE',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4003,
    job_title: 'Store Manager',
    department: 'Brand Bazaar',
    location: 'UAE',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4186,
    job_title: 'DC Assistant',
    department: 'Distribution Centre Riyadh Office-KSA',
    location: 'Riyadh, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 2729,
    job_title: 'Executive - Finance - ecommerce',
    department: 'X Ecommerce X',
    location: 'KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4086,
    job_title: 'Beauty Advisor',
    department: 'Inglot Kuwait',
    location: 'Kuwait',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4232,
    job_title: 'Marketing Executive',
    department: 'R&B Kids Office',
    location: 'UAE',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 3934,
    job_title: 'Sales Associate',
    department: 'Brand Bazaar',
    location: 'UAE',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 3935,
    job_title: 'Stock Coordinator',
    department: 'Brand Bazaar',
    location: 'UAE',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 3836,
    job_title: 'Sales Associate',
    department: 'Brand Bazaar',
    location: 'UAE',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4166,
    job_title: 'Project Engineer',
    department: 'Projects KSA',
    location: 'Riyadh, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4027,
    job_title: 'Senior Crew',
    department: 'Coldstone Creamery Al Khiran Mall',
    location: 'Kuwait',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 3850,
    job_title: 'Assistant Store Manager',
    department: 'Steve Madden',
    location: 'Dubai, UAE',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4159,
    job_title: 'Cashier',
    department: 'Rituals',
    location: 'UAE',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4238,
    job_title: 'Manager - Marketing',
    department: 'R&B Kids Office',
    location: 'UAE',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4126,
    job_title: 'Store Manager',
    department: 'Steve Madden',
    location: 'Kuwait',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4060,
    job_title: 'Assistant Store Manager',
    department: 'Tim Hortons Sales & Operations',
    location: 'KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 2293,
    job_title: 'Sales Associate - R&B',
    department: 'R&B KSA',
    location: 'Dammam, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 2846,
    job_title: 'Sales Associate',
    department: 'Crocs Al Khobar Trading',
    location: 'Khobar, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4132,
    job_title: 'Senior Executive - Marketing',
    department: 'Tim Hortons Marketing',
    location: 'KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 2810,
    job_title: 'Sales Associate - R&B',
    department: 'R&B',
    location: 'KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4221,
    job_title: 'Regional Finance Controller',
    department: 'Tim Hortons Accounts and Finance',
    location: 'KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 3791,
    job_title: 'Government Relations Officer',
    department: 'Government Relations',
    location: 'Riyadh, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4059,
    job_title: 'DC Assistant',
    department: 'Distribution Centre Kuwait',
    location: 'Kuwait',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4088,
    job_title: 'Visual Merchandiser',
    department: 'Calvin Klein Kuwait',
    location: 'Kuwait',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4261,
    job_title: 'Manager - Accounts & Finance',
    department: 'Accounts and Finance UAE',
    location: 'Dubai, UAE',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4229,
    job_title: 'Senior Buyer',
    department: 'R&B Kids Office',
    location: 'UAE',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 3961,
    job_title: 'Assistant Manager - Reporting & Analytics',
    department: 'Club Apparel Customer Loyalty UAE',
    location: 'Dubai, UAE',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4108,
    job_title: 'Warehouse Driver',
    department: 'Distribution Centre',
    location: 'Riyadh, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4216,
    job_title: 'Waiter',
    department: 'Sushi Library Nakheel Mall - Dammam',
    location: 'Dammam, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4155,
    job_title: 'Assistant Store Manager',
    department: 'Crocs Riyadh Park Mall',
    location: 'Riyadh, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4241,
    job_title: 'Executive - Accounts',
    department: 'Fuel Buddy',
    location: 'UAE',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 3881,
    job_title: 'Sales Associate',
    department: 'R&B Head Office KSA',
    location: 'Dammam, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4242,
    job_title: 'Internal Auditor',
    department: 'Tim Hortons Internal Audit',
    location: 'KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 3372,
    job_title: 'Store Manager',
    department: 'Human Capital KSA',
    location: 'Jeddah, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 3889,
    job_title: 'Service Crew',
    department: 'Tim Hortons Tawuniya Tower Riyadh',
    location: 'Riyadh, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 3422,
    job_title: 'Sales Associate',
    department: 'Crocs',
    location: 'UAE',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 2587,
    job_title: 'Assistant Manager - Sales',
    department: 'Human Capital',
    location: 'UAE',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4165,
    job_title: 'Accountant',
    department: 'Tim Hortons Accounts and Finance',
    location: 'KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 3490,
    job_title: 'Supervisor',
    department: 'R&B Al Salaam Mall',
    location: 'Jeddah, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4100,
    job_title: 'Stock Coordinator',
    department: 'LC Waikiki Kuwait',
    location: 'Kuwait',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4252,
    job_title: 'Assistant Manager - Logistics',
    department: 'Central Logistics',
    location: 'Riyadh, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4178,
    job_title: 'Receptionist',
    department: 'Adminstration Qatar',
    location: 'Qatar',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 2561,
    job_title: 'Sales Associate - ARD - Riyadh',
    department: 'Ardene Othaim Mall-Rabwa ',
    location: 'Riyadh, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4253,
    job_title: 'Assistant - Inventory Scanning',
    department: 'Inventory KSA',
    location: 'Jeddah, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4270,
    job_title: 'Technician - Audio & Video',
    department: 'UAE Information and Communication Technology',
    location: 'UAE',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4191,
    job_title: 'Stock Coordinator',
    department: 'Tommy Hilfiger',
    location: 'UAE',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4231,
    job_title: 'Manager - Ecommerce',
    department: 'Beverly Hills Polo Club Corporate',
    location: 'UAE',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 3940,
    job_title: 'Supervisor',
    department: 'Sprinklez Jamies Pizzeria Office',
    location: 'Kuwait',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4192,
    job_title: 'Data Entry Operator',
    department: 'Distribution Centre Riyadh Office-KSA',
    location: 'Riyadh, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4032,
    job_title: 'Accountant',
    department: 'Accounts and Finance',
    location: 'Riyadh, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4194,
    job_title: 'Host',
    department: 'Sushi Library',
    location: 'KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4071,
    job_title: 'Area Sales Manager',
    department: 'Tim Hortons Sales & Operations',
    location: 'KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4193,
    job_title: 'Store Manager',
    department: 'Dune Nakheel Mall Riyadh',
    location: 'KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 3185,
    job_title: 'Graphic Designer',
    department: 'R&B',
    location: 'UAE',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4230,
    job_title: 'Manager - Marketing',
    department: 'Beverly Hills Polo Club Corporate',
    location: 'UAE',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4092,
    job_title: 'Senior Store Manager',
    department: 'The Childrens Place Avenues Mall',
    location: 'Kuwait',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4171,
    job_title: 'Sales Associate',
    department: 'Human Capital KSA',
    location: 'Riyadh, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4154,
    job_title: 'Stock Coordinator',
    department: 'Beverly Hills Polo Club Al Kifah Plaza - Khobar',
    location: 'Riyadh, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4234,
    job_title: 'Ecommerce Manager - Marketplace',
    department: 'R&B Kids Office',
    location: 'UAE',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4188,
    job_title: 'Maintenance Technician',
    department: 'Projects KSA',
    location: 'Riyadh, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4224,
    job_title: 'Cash Collector',
    department: 'Tim Hortons Accounts and Finance',
    location: 'KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4225,
    job_title: 'Loss Prevention Associate',
    department: 'Tim Hortons Loss Prevention',
    location: 'KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4226,
    job_title: 'Assistant Manager - Internal Audit & Loss Prevention',
    department: 'Tim Hortons Loss Prevention',
    location: 'KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4227,
    job_title: 'Operations Manager',
    department: 'Tim Hortons Sales & Operations',
    location: 'KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 4269,
    job_title: 'Sales Associate',
    department: 'R&B Head Office KSA',
    location: 'Riyadh, KSA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 2023091,
    job_title: 'Senior Manager - Internal Audit',
    department: 'Internal Audit',
    location: 'Gurgaon Office, INDIA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 2023092,
    job_title: 'Senior Manager',
    department: 'Ecommerce Finance',
    location: 'Mumbai Office, INDIA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 2023093,
    job_title: 'Accounts Executive',
    department: 'Accounts',
    location: 'Ahmedabad Office, INDIA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 2023094,
    job_title: 'Store Manager',
    department: 'Bath & Body Works',
    location: 'Nexus Mall, Amritsar, INDIA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 2023095,
    job_title: 'Store Manager',
    department: 'Aldo',
    location: 'Irrum Manzil, Hyderabad, INDIA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
  {
    requisition_number: 2023096,
    job_title: 'Store Manager',
    department: 'La vie en Rose',
    location: 'Mall of Asia, Bangalore, INDIA',
    recruiter_email: 'globalijp@apparelgroup.in',
  },
];
